import os
import re
import sys
import time
import shutil


configfile: "config/config.yaml"


include: "rules/patterns.smk"
include: "rules/common.smk"


DRY_RUN = any("-n" in arg for arg in sys.argv[1:])
INCOMPLETE_FILES = move_incomplete_files(
    config.get("incomplete_files"), is_dry_run=DRY_RUN
)
RUN_DIRS, SUBRUN_DIRS, FLOWCELL_DIRS = get_run_dir_wcs(rgx_dir_pattern=RGX_DIR_PATTERN)


wildcard_constraints:
    run_dir="|".join(RUN_DIRS),
    subrun_dir="|".join(SUBRUN_DIRS),
    flowcell="|".join(FLOWCELL_DIRS),


# Check status of run by doing dry-run. If non-zero and error msg contaings IncompleteOutputException, update config wiht rebasecall.
# Then change params and output to include previous file.
rule dorado_basecaller:
    input:
        dorado_bin=config["dorado"]["bin"],
        pod5_directory=os.path.join(
            config["input_dir"], "{run_dir}", "{subrun_dir}", "{flowcell}", "pod5"
        ),
        rebasecall_file=lambda wc: (
            INCOMPLETE_FILES[expand_path(wc, READS_FILE)]
            if INCOMPLETE_FILES.get(expand_path(wc, READS_FILE))
            else []
        ),
    output:
        reads=os.path.join(
            OUTPUT_DIR,
            "{run_dir}.bam",
        ),
        marker_file=touch(os.path.join(OUTPUT_DIR, "basecalling.done")),
    resources:
        devices="all",
    params:
        rebasecall_file=lambda wc, input: (
            f"--resume-from {input.rebasecall_file}" if input.rebasecall_file else ""
        ),
        recursive="--recursive",
        model=config["dorado"]["model"],
        modifications=config["dorado"]["modifications"],
        min_qscore=config["dorado"]["min_qscore"],
    # Only allow up to one process at a time.
    threads: workflow.cores
    log:
        "logs/dorado_basecaller/{run_dir}_{subrun_dir}_{flowcell}.log",
    benchmark:
        "benchmarks/dorado_basecaller/{run_dir}_{subrun_dir}_{flowcell}.tsv"
    shell:
        """
        {input.dorado_bin} basecaller \
            {params.model},{params.modifications} \
            {params.recursive} \
            --min-qscore {params.min_qscore} \
            --device cuda:{resources.devices} \
            {params.rebasecall_file} \
            {input.pod5_directory} > {output.reads} 2> {log}
        """


# TODO: Convert to fastq.gz and then error correct.


rule all:
    input:
        expand(
            rules.dorado_basecaller.output,
            zip,
            run_dir=RUN_DIRS,
            subrun_dir=SUBRUN_DIRS,
            flowcell=FLOWCELL_DIRS,
        ),
    default_target: True
